CONFIG_CONSOLE=y
CONFIG_I3C=y
CONFIG_PRINTK=y
CONFIG_P3T1755=y
CONFIG_SERIAL=y
CONFIG_SENSOR=y
CONFIG_UART_CONSOLE=y
CONFIG_MAIN_STACK_SIZE=1024
CONFIG_CMSIS_DSP=y
CONFIG_CMSIS_DSP_COMPLEXMATH=y
CONFIG_CMSIS_DSP_TRANSFORM=y
